language: cpp

os:
  - linux
  - osx

env:
  - SHARED=1
  - SHARED=0

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARED_LIBS=$SHARED

addons:
  apt:
    packages:
      - libboost-test-dev

script: make # && make test