version: '{build}'
clone_folder: c:\projects\dicenotation
image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
    - SHARED: 1
    - SHARED: 0
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G Ninja -DBUILD_SHARED_LIBS=%SHARED%

build_script:
  - cmd: cmake . --build

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
